spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: preuser-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:19090/eureka/

  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_SERVER_HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

  endpoint:
    health:
      show-details: always

    prometheus:
      access: unrestricted

server:
  port: 19096
