spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: preuser-service


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:19090/eureka/

  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_SERVER_HOSTNAME}

server:
  port: 8081