spring:
  application:
    name: preuser-service

  datasource:
    url: jdbc:postgresql://localhost:5432/limited
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
